plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.1.0'
group = 'com.ironmod'
base {
    archivesName = 'ironmod'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                ironmod {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                ironmod {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net/' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

// A resources.srcDir 'src/generated/resources' pode ser usada se você usar data generation

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
        minecraft_version: '1.20.1', minecraft_version_range: '[1.20.1,1.21)',
        forge_version: '47.2.0', forge_version_range: '[47,)',
        loader_version_range: '[47,)',
        mod_id: 'ironmod', mod_name: 'Iron Suit Mod',
        mod_license: 'MIT', mod_version: version,
        mod_authors: 'Você', mod_description: 'Mod de armaduras modulares estilo Homem de Ferro.'
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties + [project: project]
    }
}
